### ISSUE TITLE
Error handling after future timeout

### ISSUE THREAD

**Issue by janniclas** [delphi-hub/delphi-registry#96] opened 2019-01-31 10:21 UTC
If an instance times out during startup (future timeout) we get a strange behavior. The instance has been added to the database successfully but timed out during connection to the docker host. But nonetheless the instance was not removed afterwards and was reported with state deploying to the management application

**Comment by johannesduesing** [comment] 2019-02-21 08:12
I'm currently not able to reproduce this, thus moving it to the next milestone.

**Comment by 24santoshr** [comment] 2019-03-21 16:22
Referring #131

**Comment by johannesduesing** [comment] 2019-03-28 12:12
Closed with #131

**Closed as completed by johannesduesing** 2019-03-28 12:12 UTC
Labels: bug
